EveGetter/apps/UsersProfiles/urls.py
from django.urls import path, include
from . import views 
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve
from .views import myEventsList, myTickets, UserLookUp
from django.contrib.auth import views as auth_views


urlpatterns = [ 
   # url(r'^', include('django.contrib.auth.urls')),
   path(r'^register/$', views.registerPage, name='register'),   
   path(r'^login/$', views.loginPage, name="login"),
   path(r'^logout/$', views.logoutUser, name="logout"),
   path(r'^myaccount/$', views.accountControl, name="acclook"),
   path(r'^change_info/$', views.UpdateUser, name="updateuser"),
   path(r'^myevents/$',myEventsList.as_view(), name="myevents"),
   path(r'^mytickets/$', myTickets.as_view(), name="mytickets"),
   path(r'^userlook/<int:pk>/$', views.UserLookUp, name='look_for_user'),
   # path(r'^reset_password/$', auth_views.PasswordResetView.as_view(template_name='accounts/password_reset.html'), name="reset_password"),
   # path(r'^reset_password_sent/$', auth_views.PasswordResetDoneView.as_view(template_name='accounts/password_reset_sent.html'), name="reset_password_done"),
   # path(r'^reset/<uidb64>/<token>/$', auth_views.PasswordResetConfirmView.as_view(), name="reset_password_confirm"),
   # path(r'^reset_password_complete/$', auth_views.PasswordResetCompleteView.as_view(), name="reset_password_complete"),



   #path(r'^change-password/$', views.change_password, name="change_password"),
]

EveGetter/apps/events/urls.py
from django.urls import path, re_path
from .views import (EventDetailView, EventDetailTicketBuy,
TicketBuy, MainPageListView, AllEventsDisplay,
EventLookUpCreator,
EventUpdateTickets,EventDetailView_true,
EventDetailTicketGift, TicketReturn,)
from . import views 
from django.conf.urls import url
from UsersProfiles.views import *
##TEST##
from .views import *


urlpatterns = [
    ####TEST#####
   # path('', EventList),
  # path("event_listing/", EventListing.as_view(), name='listing'),
   # path("ajax/event_type/", getEvent_type, name='get_event_type'),
  #  path("ajax/age/", getAge_start, name='get_age'),
   # path("ajax/date/", getDate, name='get_date'),
    ####TEST##########

    path('', views.MainPageListView,name='index'),
    path('events/all/',views.AllEventsDisplay, name='allevents'),
    path(r'^event/<int:pk>/$', views.EventDetailView_true, name='event-detail'),
    path('event/<int:pk>/redact/',views.UpdateEvent, name='event-redact'),
    path('event/<int:pk>/report/', views.EventLookReport, name='event-creator-report'),
    path('event/<int:pk>/creatorlook/', EventLookUpCreator, name='event-creator-detail'),
    # path('event/<int:pk>/creatorlook/', EventLookUpCreator.as_view(), name='event-creator-detail'),
    path('event/<int:pk>/tickets/create/',views.EventCreateTickets, name='create-tickets'),
    path('event/<int:pk>/tickets/update/', views.EventUpdateTickets, name='tickets-redact'),
    path('events/create/', views.createEvent, name='createEvent'),
    path('event/<int:pk>/tickets/gift', EventDetailTicketGift.as_view(), name='ticket-gift'),
    path('event/<int:pk>/tickets/buy/', EventDetailTicketBuy.as_view(), name='event-tickets-buy'),
    path('event/<int:pk>/tickets/gift/acc', views.TicketGiftDone, name='ticket-gift-acc'),
    path('event/<int:pk>/tickets/buy/done', views.TicketBuy, name='saveticket'),
    path('event/<int:pk>/tickets/alltickets', views.TicketAll, name='event-all-tickets'),
    path(r'^mytickets/<int:pk>/$',views.TicketReturn, name="ticket-return"),
    # path('myevents2/', artists_view, name='myevents_test'),

    
]

EveGetter/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve


urlpatterns = [

    path(r'^$',include('UsersProfiles.urls')),
    path('',include('events.urls')),
    path('admin/', admin.site.urls),
    # url(r'^', include('django.contrib.auth.urls')),
    #url(r"^event/", include(("events.urls", "events"), namespace= "events"))

] 

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

EveGetter/apps/events/models.py
from UsersProfiles.models import Account, GenderRestriction
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.db.models.signals import post_save, pre_save
from django.dispatch import receiver
from django.shortcuts import get_object_or_404
from django.urls import reverse

# Create your models here.
class Event(models.Model):
    event_creator = models.ForeignKey(Account, on_delete = models.CASCADE)
    name = models.CharField("event name", max_length=30, blank=False)
    description = models.TextField("description", blank=False)
    short_description = models.TextField("short description", blank=False)
    date = models.DateField("event date", blank=False)
    time = models.TimeField("event time", blank=True, null=True)
    duration = models.TimeField("duration of event", blank=True, null=True)
    if_dresscode = models.BooleanField("if dresscode", blank=True)
    dresscodevalue = models.CharField("dress code restriction", max_length=30, blank=True)
    if_age = models.BooleanField("if age",blank=True)
    age_start = models.IntegerField("from what age restriction", blank=True, default=0)
    age_end = models.IntegerField("till what age restriction", blank=True, default=0)
    if_gender = models.BooleanField("if gender", blank=True)
    sex = models.ForeignKey(GenderRestriction,null=True, on_delete=models.CASCADE, blank=True) 
    insidespendings = models.BooleanField("spendings restriction", blank=True)
    country = models.CharField("country", max_length=30, blank=True)
    city = models.CharField("city", max_length=30, default="", blank=True)
    event_adress = models.CharField("event adress", max_length=30, default="", blank=False)
    expected_event = models.BooleanField("if paid expectation", default=False, blank=True)
    event_type = models.ForeignKey('EventType', on_delete=models.CASCADE, blank=False)
    deposit = models.BooleanField("if deposited",default=False, blank=True)
    if_ticket_created = models.BooleanField("if it has tickets", default=False, blank=True)
    moderation = models.ForeignKey('EventModeration', on_delete=models.PROTECT, blank=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('event-creator-detail', kwargs={'pk': self.pk})
#@receiver(pre_save, sender=Event, dispatch_uid="set_moderate")
#def set_moderatevtion_level(sender, instance, **kwargs):
#    get_mod_ins = EventModeration.objects.get(eventstatus = 'inactive')
#    instance.moderation = get_mod_ins
#    instance.save()


class EventModeration(models.Model):
    eventstatus = models.CharField(max_length=20, default="inactive")

    def __str__(self):
        return self.eventstatus

#Фотографии
class Images(models.Model):
    event = models.ForeignKey(Event, on_delete = models.CASCADE)
    image = models.ImageField(upload_to='events_images', verbose_name='Фотография', blank=False, null=True)

    def __str__(self):
        return self.event.name + "Image"


class UsersTicketsStatus(models.Model):
    status_name = models.CharField(max_length=30)

    def __str__(self):
        return self.status_name


class Ticket(models.Model):
    ticket_name = models.CharField("ticket name", max_length=25, blank=False)
    amount = models.IntegerField("amount of ticket", blank=False) 
    price = models.IntegerField("ticket's price", blank=False)
    description = models.CharField("ticket description", max_length=100, blank=False)
    event = models.ForeignKey('Event', on_delete=models.PROTECT)
    amount_left = models.IntegerField("amount left", blank=False)
    #ticket_holder = models.ManyToManyField(Account)
    
    def __str__(self):
        return self.ticket_name
    


@receiver(post_save, sender=Ticket, dispatch_uid="update_ticket_created")
def update_ticket_created(sender, instance, **kwargs):
    instance.event.if_ticket_created = True
    instance.event.save()


class UsersTickets(models.Model):
    ticket_owner = models.ForeignKey(Account, related_name="ticketholder", on_delete=models.PROTECT)
    ticket_idpk = models.ForeignKey(Ticket, on_delete=models.PROTECT)
    count = models.IntegerField(default=1)
    date_bought = models.DateField("date of purchase", auto_now_add=True)
    if_gift = models.BooleanField("If ticket was gifted", default=False)
    status = models.ForeignKey(UsersTicketsStatus, on_delete=models.PROTECT, default=1)

    def __str__(self):
        return '{}-{}'.format(self.ticket_idpk.ticket_name, str(self.ticket_idpk))

@receiver(post_save, sender=UsersTickets, dispatch_uid="decrease_tickets_amount")
def decrease_ticket_amount(sender, instance, **kwargs):
    instance.ticket_idpk.amount_left -= instance.count
    instance.ticket_idpk.save()

class EventType(models.Model):
    name = models.CharField('name of eventtype', max_length=25)

    def __str__(self):
        return self.name

class EventComment(models.Model):
    event = models.ForeignKey(Event, on_delete = models.CASCADE)
    user = models.ForeignKey(Account, on_delete = models.CASCADE)
    text = models.TextField(max_length = 160)
    time_created = models.DateTimeField(default = timezone.now, null = True)
   # moderation = models.BooleanField(default = False)

    def __str__(self):
        return '{}-{}'.format(self.event.name, str(self.user.first_name))
     #   return self.text


class Countries(models.Model):
    country = models.CharField(max_length=30, blank=True)

    def __str__(self):
        return self.country

class Cities(models.Model):
    city = models.CharField(max_length=30, blank=True)
    countryid = models.ForeignKey(Countries, on_delete=models.CASCADE)

    def __str__(self):
        return self.city

    

EveGetter/apps/UsersProfiles/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.forms import inlineformset_factory
from django.contrib.auth.forms import UserCreationForm, PasswordChangeForm
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import Http404
from .forms import CreateUserForm, PasswordChangeFormEdit, UserUpdateForm
from events import urls
from .models import Account
from events.models import Event, Ticket, UsersTickets
from django.views.generic.list import ListView
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import get_object_or_404
from django.utils.decorators import method_decorator
from django.template.loader import render_to_string
from django.http import JsonResponse
# Create your views here.
#####TESTSEARCH#####
# def artists_view(request):
#   ctx = {}
#   url_parameter = request.GET.get('q')

#   if url_parameter:
#     user_events = Event.objects.filter(name__icontains=url_parameter)
#   else:
#     user_events = Event.objects.all()

#   ctx['user_events'] = user_events
#   if request.is_ajax():

#     html = render_to_string(
#       # template_name='accounts/my_event_test_display.html', 
#       context={"user_events": user_events}
#     )
#     data_dict = {'html_from_view': html}
#     return JsonResponse(data=data_dict, safe=False)

#   return render(request, 'accounts/my_events_test.html', context=ctx)



def registerPage(request):
  form = CreateUserForm()

  if request.method == 'POST':
    form = CreateUserForm(request.POST)
    if form.is_valid():
      # form.cleaned_data()
      form.save()
      messages.success(request,'Вы успешно зарегестрировались!')

      return redirect('login')

  context = {'form': form}
  return render(request, 'accounts/register.html', context)


def loginPage(request):
  if request.user.is_authenticated:
    return redirect('index')
  else:
    if request.method == 'POST':
      phone = request.POST.get('phone')
      password = request.POST.get('password')
      user = authenticate(request, phone=phone, password=password)

      if user is not None:
        login(request, user)
        return redirect('index')
      
      else: 
        messages.info(request, 'Телефон или пароль неправильный')
    context = {}
    return render(request, 'accounts/login.html', context)


def logoutUser(request):
  logout(request)
  return redirect('index')



    



@login_required(login_url='login')
def accountControl(request):
  form = PasswordChangeFormEdit(user=request.user)
  if request.method == 'POST':
    form = PasswordChangeFormEdit(data=request.POST, user=request.user)

    if form.is_valid():
      # form.cleaned_data()
      form.save()
      update_session_auth_hash(request, form.user)
      return redirect('acclook')

  else:
    form = PasswordChangeFormEdit(user=request.user)    
  return render(request, 'accounts/acc_control.html', context = {'form':form})


@login_required(login_url='login')
def UpdateUser(request):
  if request.method == 'POST':
    u_form = UserUpdateForm(request.POST, request.FILES, instance=request.user)
    if u_form.is_valid():
      text = u_form
      text.user_avatar = u_form.cleaned_data['user_avatar']
      text.save()
      messages.success(request, f'Вы обновили информацию')
      return redirect('acclook')
  else:
    u_form = UserUpdateForm(instance=request.user)

  context = {
    'u_form': u_form
  }  
  return render(request, 'accounts/change_acc_info.html', context)



def UserLookUp(request,pk):
  user = get_object_or_404(Account, id=pk)
  context = {
    'user': user,
  }
  return render(request, 'accounts/user_lookup.html', context)



# @login_required(login_url='login')
class myEventsList(ListView):
  model = Event
  template_name='accounts/my_events.html'

  def get_context_data(self, **kwargs):
    context = super().get_context_data(**kwargs)

    context['user_events'] = Event.objects.filter(event_creator=self.request.user)
    paginator = Paginator(context['user_events'],4)
    page = self.request.GET.get('page')
    try:
      context['user_events'] = paginator.page(page)
    except PageNotAnInteger:
      context['user_events'] = paginator.page(1)
    except EmptyPage:
      context['user_events'] = paginator.page(paginator.num_pages)
    
    return  context

  @method_decorator(login_required(login_url='login'))
  def dispatch(self, *args, **kwargs):
    return super(myEventsList, self).dispatch(*args, **kwargs)

@login_required(login_url='login')
def myEvents(request):
  user_events = Event.objects.filter(event_creator=request.user)
  return render(request, 'accounts/my_events.html', context={'user_events':user_events})

# @login_required(login_url='login')
class myTickets(ListView):
  model = UsersTickets
  template_name = 'accounts/my_tickets.html'

  def get_context_data(self, **kwargs):
    context = super().get_context_data(**kwargs)

    context['user_tickets'] = UsersTickets.objects.filter(ticket_owner=self.request.user).filter(status=1)
    paginator = Paginator(context['user_tickets'],4)
    page = self.request.GET.get('page')
    try:
      context['user_tickets'] = paginator.page(page)
    except PageNotAnInteger:
      context['user_tickets'] = paginator.page(1)
    except EmptyPage:
      context['user_tickets'] = paginator.page(paginator.num_pages)
    
    return  context

  @method_decorator(login_required(login_url='login'))
  def dispatch(self, *args, **kwargs):
    return super(myTickets, self).dispatch(*args, **kwargs)

EveGetter/templates/accounts/acc_control.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Профиль{% endblock %}
{% block breadcrumbs %}
  <li><a href="" class="bread_current">{{request.user.first_name}} {{request.user.second_name}}</a></li>
{% endblock %}
{% block content %}
      <div class="menu_section">
        <a href="{% url 'mytickets' %}">Мои билеты</a>
        <a href="{% url 'myevents' %}">Мои мероприятия</a>
        <a href="#">Помощь</a>
        <a href="{% url 'logout' %}">Выйти</a>
      </div>
      <div class="acc_top_1__3">
        <div class="acc_top_1__3_img">
          <img src=" {{ request.user.user_avatar.url }} " >
          <!-- <a href="#">Изменить фото</a> -->
        </div>
        <div class="acc_top_1__3_info">
          <p>{{request.user.first_name}} {{request.user.second_name}}</p>
          <p>{{request.user}}</p>
          <p>{{request.user.email}}</p>
        </div>
        <div class="acc_top_1__3_rank">
          <div class="acc_top_1__3_rank_circle">
            <a href="#">10/10</a>
          </div>
        </div>
      </div>
      <div>
      </div>
      <div class="hidden">
        <form action="" method="POST" class = "popup_pass" id="form">
          {% csrf_token %}
          {{ form.as_p }}
          <button type="submit">Сохранить</button>
        </form>
      </div>
      <div class="acc_top_2__3">
        <!-- <a href="#" class="change_info ">Изменить персональную информацию</a> -->
        <a href="{% url 'updateuser' %}">Редактировать профиль</a>
        <a href="#form" class="change_pass popup">Сменить пароль</a>
        <!-- <a href="#" class="add_que">Добавить контрольный вопрос</a> -->
        <!-- <a href="#" class="change_numb">Сменить номер телефона</a> -->
      </div>
{% endblock %}

EveGetter/templates/accounts/change_acc_info.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Редактировать профиль{% endblock %}
{% block content %}
<h1>Ваши данные</h1>
    <form action="" method="POST" enctype="multipart/form-data">
        <div class="div_change_user_info">
                {% csrf_token %}
                <h3>Имя</h3>
                {{u_form.first_name}}
                <h3>Фамилия</h3>
                {{u_form.second_name}}
                <h3>Почта</h3>
                {{u_form.email}}
                <h3>День рождения</h3>
                {{u_form.birth_date}}
                <h3>Пол</h3>
                {{u_form.sex}}
                <h3>Страна</h3>
                {{u_form.country}}
                <h3>Город</h3>
                {{u_form.city}}
                <h3>Описание профиля</h3>
                {{u_form.profile_status}}
                <h3>Фото</h3>         
            {{u_form.user_avatar}}
            <button type="submit" class="">Сохранить</button>
        </div>
    </form>    
{% endblock %}

EveGetter/templates/accounts/my_event_test_display.html
{% if user_events %}      
      <div class="my_tickets_cards_top">
        {% for a in user_events %}
        <div class="div_main_card1 div_my_tickets_cards">
            <div class="main_card_img">
              <div class="card_img">
                {% with a.images_set.all.0 as ph1%}
                  <img src="{{ph1.image.url}}" alt="">
                {% endwith %}
              </div>
              <div class="main_card_img_info ">
                <div class="">
                  <a href="#">{{a.ticket_set.all.0.price}}₽</a>
                </div>
                <div class="">
                  <a href="{% url 'event-creator-detail' a.id %}">Подробнее</a>
                </div>
                <div class="">
                {% if a.if_ticket_created == False %}
                  <a href="{% url 'create-tickets' a.id %}">Создать билеты</a>
                {% else %}
                <a href="{% url 'event-all-tickets' a.id %}">Билеты</a>
                {% endif %}
                </div>
              </div>
            </div>
            <div class="main_card_name">
              <a class="name_links" href="{% url 'event-detail' a.id %}">{{a.name}}</a> 
            </div>
            <div class="main_card_date_place_2">
              <a class="main_card_date_place_links" href="#">{{a.date}}, {{a.city}}</a>
            </div>
            {% if a.moderation.id == 1 %}
            <div class="moder_div_events">
              <span class="red_font_span">На модерации</span>
            </div>            
            {% else %}
            <div class="moder_div_events">
              <span class="green_font_span">Модерация пройдена</span>
            </div>
            {% endif %}
        </div>
        {% endfor %}
      </div>
      {% else %}
      <h1>У вас еще нет мероприятий</h1>
      {% endif %}

EveGetter/templates/accounts/my_events.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Мои мероприятия{% endblock %}
{% block breadcrumbs %}
  <li><a href="{% url 'acclook' %}" class="bread_active">{{request.user.first_name}} {{request.user.second_name}}</a></li>
  <li><a href="" class="bread_current">Мои мероприятия</a></li>
{% endblock %}
{% block content %}
      <section class="section_filter">
        <div class="main_filter_my_tickets ">
          <div class="event_type_div event_type_div_my_tickets event_type_div_my_events">
            <select class="event_type_filter"  >
              <option selected disabled hidden>Статус</option>
              <option>Предстоит</option>
              <option>Завершено</option>
            </select>
          </div>
          <div class="event_type_div event_type_div_my_tickets div_filter_deposite">
            <select class="event_type_filter"  >
              <option selected disabled hidden>Депозит</option>
              <option>Внесен</option>
              <option>Не внесен</option>
            </select>
          </div>
          <div class="date_picker_div date_picker_div_my_tickets">
            <input class="date_picker date_picker_my_tickets" type="text" name="daterange" value="01/01/2018 - 01/15/2018" />
          </div>
          <div class = "TicketsSearch">
            <form class="TicketsForm">
              <input class="Ticketsinput" type="text" placeholder="Название мероприятия">
              <button class="searchbutton searchbutton_my_tickets" type="submit"></button>
            <form>
          </div>
        </div>
      </section>
      <div class="my_events_cards">
        <h2>Мои мероприятия</h2>
      </div>
      {% if user_events %}
      
      <div class="my_tickets_cards_top">
        {% for a in user_events %}
        <div class="div_main_card1 div_my_tickets_cards">
            <div class="main_card_img">
              <div class="card_img">
                {% with a.images_set.all.0 as ph1%}
                  <img src="{{ph1.image.url}}" alt="">
                {% endwith %}
              </div>
              <div class="main_card_img_info ">
                <div class="">
                  <a href="#">{{a.ticket_set.all.0.price}}₽</a>
                </div>
                <div class="">
                  <a href="{% url 'event-creator-detail' a.id %}">Подробнее</a>
                </div>
                <div class="">
                {% if a.if_ticket_created == False %}
                  <a href="{% url 'create-tickets' a.id %}">Создать билеты</a>
                {% else %}
                <a href="{% url 'event-all-tickets' a.id %}">Билеты</a>
                {% endif %}
                </div>
              </div>
            </div>
            <div class="main_card_name">
              <a class="name_links" href="{% url 'event-detail' a.id %}">{{a.name}}</a> 
            </div>
            <div class="main_card_date_place_2">
              <a class="main_card_date_place_links" href="#">{{a.date}}, {{a.city}}</a>
            </div>
            {% if a.moderation.id == 1 %}
            <div class="moder_div_events">
              <span class="red_font_span">На модерации</span>
            </div>            
            {% else %}
            <div class="moder_div_events">
              <span class="green_font_span">Модерация пройдена</span>
            </div>
            {% endif %}
        </div>
        {% endfor %}
      </div>

      {% else %}
      <h1>У вас еще нет мероприятий</h1>
      {% endif %}
      <div class="reviews_pagination_all">
        <div class="reviews_pagination_creator">
            <nav id="pagination">
                <ul class="pagination justify-content-center">
                    {% if user_events.has_previous %}
                        <li class="page-item">
                            <a href="{{ request.path }}?page={{ user_events.previous_page_number }}" class="page-link">&laquo;</a>
                        </li>
                    {% else %}
                        <li class="page-item disabled">
                            <a href="#" class="page-link" tabindex="-1" aria-disabled="true">&laquo;</a>
                        </li>
                    {% endif %}
                    {% if user_events.paginator.count > user_events.paginator.page_range%}
                    <li class="page-item disabled">
                      <a href="#" class="page-link disabled" aria-disabled="true">1</a>
                    </li>            
                    {% else %}
                    {% for i in user_events.paginator.page_range %}
                        {% if user_tuser_eventsickets.number == 1 %}
                            <li class="page-item ">
                                <a href="{{ request.path }}?page={{ i }}" class="page-link">{{ i }}</a>
                            </li>
                        {% else %}
                        <li class="page-item">
                            <a href="{{ request.path }}?page={{ i }}" class="page-link">{{ i }}</a>
                        </li>
                        {% endif %}
                    {% endfor %}
                    {% if user_events.has_next %}
                        <li class="page-item">
                            <a href="{{ request.path }}?page={{ user_events.next_page_number }}" class="page-link">&raquo;</a>
                        </li>
                    {% else %}
                        <li class="page-item disabled">
                            <a href="#" class="page-link disabled" tabindex="-1" aria-disabled="true">&raquo;</a>
                        </li>
                    {% endif %}
                    {% endif %}            
                </ul>
            </nav>
        </div>
    </div>
    <div class="event_create">
      <a href="{% url 'createEvent' %}">Создать мероприятие</a>
    </div>
    {% endblock %}

EveGetter/templates/accounts/my_tickets.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Мои билеты{% endblock %}
{% block breadcrumbs %}
  <li><a href="{% url 'acclook' %}" class="bread_active">{{request.user.first_name}} {{request.user.second_name}}</a></li>
  <li><a href="" class="bread_current">Билеты</a></li>
{% endblock %}
{% block content %}
    <section class="section_filter">
      <div class="main_filter_my_tickets ">
        <div class="event_type_div event_type_div_my_tickets">
          <select class="event_type_filter"  >
            <option selected disabled hidden>Статус</option>
            <option>Предстоит</option>
            <option>Завершено</option>
          </select>
        </div>
        <div class="date_picker_div date_picker_div_my_tickets">
          <input class="date_picker date_picker_my_tickets" type="text" name="daterange" value="01/01/2018 - 01/15/2018" />
        </div>
        <div class = "TicketsSearch">
          <form class="TicketsForm">
            <input class="Ticketsinput" type="text" placeholder="Название мероприятия">
            <button class="searchbutton searchbutton_my_tickets" type="submit"></button>
          <form>
        </div>
      </div>
    </section>
    <div class="my_tickets_cards">
      <h2>Мои билеты</h2>
      {% if user_tickets %}
      <div class="my_tickets_cards_top">
        {% for a in user_tickets %}
        <div class="div_main_card10 div_my_tickets_cards">
          <div class="main_card_img">
            <div class="card_img">
              {% with a.ticket_idpk.event.images_set.all.0 as ph1%}
                <img src="{{ph1.image.url}}" alt="">
              {% endwith %}
            </div>
            <div class="main_card_img_info">
              <div class="">
                <a href="#">{{a.ticket_idpk.price}}₽</a>
              </div>
              <div class="">
                <a href="#">{{a.ticket_idpk.ticket_name}}</a>
              </div>
              <div class="">
                <a href="#">{{a.ticket_idpk.event.date}}</a>
              </div>
            </div>
          </div>
            <div class="main_card_name">
              <a class="name_links" href="{% url 'event-detail' a.ticket_idpk.event.id %}">{{a.ticket_idpk.event.name}}</a>
            </div>
            <div class="main_card_date_place">
              <a class="main_card_date_place_links" href="#">{{a.ticket_idpk.event.date}}, {{a.ticket_idpk.event.city}}</a>
            </div>
            <div class="count_tickets">
              <a href="">Количество: {{a.count}}</a>
            </div>
            <div class="return_ticket_div">
              <a href="{% url 'ticket-return' a.id %}">Вернуть билет</a>
            </div>
        </div>
      {% endfor %}
      </div>
      {% else %}
      <h2>У вас еще нет ни одного билета</h2>
      {% endif %}
      <div class="reviews_pagination_all">
        <div class="reviews_pagination_creator">
            <nav id="pagination">
                <ul class="pagination justify-content-center">
                    {% if user_tickets.has_previous %}
                        <li class="page-item">
                            <a href="{{ request.path }}?page={{ user_tickets.previous_page_number }}" class="page-link">&laquo;</a>
                        </li>
                    {% else %}
                        <li class="page-item disabled">
                            <a href="#" class="page-link" tabindex="-1" aria-disabled="true">&laquo;</a>
                        </li>
                    {% endif %}
                    {% if user_tickets.paginator.count > user_tickets.paginator.page_range%}
                    <li class="page-item disabled">
                      <!-- <a href="#" class="page-link disabled" aria-disabled="true">1</a> -->
                    </li>            
                    {% else %}
                    {% for i in user_tickets.paginator.page_range %}
                        {% if user_tickets.number == 1 %}
                            <li class="page-item ">
                                <a href="{{ request.path }}?page={{ i }}" class="page-link">{{ i }}</a>
                            </li>
                        {% else %}
                        <li class="page-item">
                            <a href="{{ request.path }}?page={{ i }}" class="page-link">{{ i }}</a>
                        </li>
                        {% endif %}
                    {% endfor %}
                    {% if user_tickets.has_next %}
                        <li class="page-item">
                            <a href="{{ request.path }}?page={{ user_tickets.next_page_number }}" class="page-link">&raquo;</a>
                        </li>
                    {% else %}
                        <li class="page-item disabled">
                            <a href="#" class="page-link disabled" tabindex="-1" aria-disabled="true">&raquo;</a>
                        </li>
                    {% endif %}
                    {% endif %}            
                </ul>
            </nav>
        </div>
    </div>
    </div>
    <div class="banner_create_event">
      <a href="{% url 'createEvent' %}">Создайте свое мероприятие вместе с нами</a>
    </div>

    {% endblock %}